### ISSUE TITLE
Extension news integrieren

### ISSUE THREAD

**Issue by phasenraum2010** [phasenraum2010/woehlkeorg_sitepackage#13]
- [ ]  #14 News-Artikel als Event mit Datum und Ort
- [ ]  #15 In der rechten Spalte Funktionen ähnlich eines Blogs 
- [ ]  #16 Google Sitemap für news Artikel
- [ ]  #17 News mit externen Seiten als Artikel 
- [ ]  #18 News mit internen Seiten als Artikel 
- [ ] #20 Seite: News-Liste
- [ ] #21 Seite: News-Artikel
