### ISSUE TITLE
Content-Migration ins News-System

### ISSUE THREAD

**Issue by phasenraum2010** [phasenraum2010/woehlkeorg_sitepackage#19]
- [ ] #32 Content-Migration von https://port80guru.tumblr.com/
- [ ] #33 Content-Migration von https://thomas-woehlke.blogspot.de/
- [ ] #34 Content-Migration von Facebook https://www.facebook.com/thomas.wohlke
- [ ] #35 Content-Migration von Twitter https://twitter.com/port80guru
- [ ] #36 Content-Migration von Google+ https://plus.google.com/u/0/+ThomasW%C3%B6hlke
- [ ] #37 Content-Migration von Mac-Foto-App
- [ ] #38 Content-Migration von Google-Fotos https://photos.google.com/
- [ ] #39 Content-Migration von YouTube 
- [ ] #40 Content-Migration von Vimeo 
- [ ] #41 Content-Migration von SlideShare 
- [ ] #42 Content-Migration von SoundCloud
- [ ]  #43 Content-Migration von StackOverflow
- [ ]  #44 Content-Migration von LastFM
- [ ]  #45 Content-Migration von Instagram
- [ ]  #46 Content-Migration von Flickr
