### ISSUE TITLE
Main Ticket for Milestone: Social Media Integration

### ISSUE THREAD

**Issue by phasenraum2010** [phasenraum2010/woehlkeorg_sitepackage#22]
- [ ] #23 import Calendar, Events
- [ ] #24 Import Persons (Accounts, Contacts, Friends, Followers) 
- [ ] #25 Import Fotos and Albums from Facebook
- [ ] #26 Import Articles from Facebook
- [ ] #27 Sharing URLs and Content
- [ ] #28 Facebook-Opengraph
- [ ] #31 Twitter-Card
