### ISSUE TITLE
Content-Migration von Vimeo 

### ISSUE THREAD

**Issue by phasenraum2010** [phasenraum2010/woehlkeorg_sitepackage#40]
- [ ] #63 Content von Vimeo: 29.05.2011 Greenpeace am Brandenburger Tor
- [ ] #62 Content von Vimeo: Hubert Weiger von BUND auf der Mahnwache am Kanzleramt nach Fukushima am 21.03.2011
- [ ] #61 Content von Vimeo: Smart Fortwo Electric Drive auf Clean Tech World 2011 Berlin
- [ ] #60 Content von Vimeo: Probefahrt mit e-Schwalbe auf der Clean Tech World 2011
- [ ] #59 Content von Vimeo: Ultima Thule
- [ ] #58 Content von Vimeo: WUT
- [ ] #57 Content von Vimeo: TESLA Roadster auf der CTW 2011 in Berlin
- [ ] #56 Content von Vimeo: Requiem TACHELES
- [ ] #55 Content von Vimeo: Kein Handicap Hamburg

**Comment by phasenraum2010** [comment]
Add Videos to Fileadmin

- [x] vimeo.com/32290974
- [x] vimeo.com/31869774
- [x] vimeo.com/31831981
- [x] vimeo.com/31831033
- [x] vimeo.com/27139404
- [x] vimeo.com/27138811

**Comment by phasenraum2010** [comment]
Add News Articles for

- [ ] vimeo.com/32290974
- [ ] vimeo.com/31869774
- [ ] vimeo.com/31831981
- [ ] vimeo.com/31831033
- [ ] vimeo.com/27139404
- [ ] vimeo.com/27138811
